### ISSUE TITLE
Comment keyboard shortcut (ctrl + /) adds // rather than #

### ISSUE THREAD

**Issue by zajrik** [junknet/vscode-nimlsp#1]
Hello! Thank you so much for writing this! I have been waiting for a VSCode extension to make use of nimlsp for quite a while now, having no idea how to go about writing one myself and not having the patience to figure it out, so I really appreciate you putting this together. I was literally just thinking about asking PMunch if he had plans for a VSCode extension earlier today before stumbling across this while looking up LSP extensions in VSCode. It's running so much smoother and snappier than the nimsuggest-based extensions.

With that said, I've encountered one small problem. Commenting selections with the keyboard shortcut (ctrl + /) prepends the highlighted lines with `//` rather than `#` which is obviously syntactically invalid in Nim. I wasn't sure if this is something that has to be addressed via the extension or via the LSP server itself. If it's the latter I'll go ahead and poke PMunch about it instead, haha.

**Comment by junknet** [comment]
fixed
